### ISSUE TITLE
Text under block caret is hard to read

### ISSUE THREAD

**Issue by zsparal** [azemoh/vscode-onedark#2]
First off all, thank you for the great color scheme!

I'm using VS Code with the Vim package which changes the style of the caret into a block (in normal mode; in insert mode it's the same as the default). I propose changing the caret color to a more neutral color (#c0c5ce works pretty nicely) to improve the contrast between the underlying text and the block caret.

A screenshot of the problem, with the fix applied on the right:
![carets](https://cloud.githubusercontent.com/assets/2189776/20432955/e316a132-ada1-11e6-9723-db91f7149c8e.png)

**Comment by azemoh** [comment]
Thanks @Gustorn for pointing this out.
