### ISSUE TITLE
bugs after last update in (pug/jade)

### ISSUE THREAD

**Issue by movasyl** [azemoh/vscode-onedark#7]
Hi, there are some errors after updating (https://github.com/azemoh/vscode-onedark/issues/6)
![default](https://cloud.githubusercontent.com/assets/14804982/21427136/7320b3d4-c85b-11e6-9592-a326e6bed283.PNG)
![2](https://cloud.githubusercontent.com/assets/14804982/21427138/7655811a-c85b-11e6-834d-94b31e411c4a.PNG)

**Comment by azemoh** [comment]
Oops. Thanks for pointing this out.

**Comment by azemoh** [comment]
Looks like this existed before that update but it's fixed now. Thanks again.

**Comment by movasyl** [comment]
No, it's thanks to you!
